login:
    path:     /login
    defaults: { _controller: PGMcdFrontendBundle:Security:login }
    
login_check:
    path: /login_check
    
pg_mcd_frontend:
    resource: "@PGMcdFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

pg_mcd_backend:
    resource: "@PGMcdBackendBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"