pg_mcd_voucher:
    resource: "@PGMcdVoucherBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:     /login
    defaults: { _controller: PGMcdBackendBundle:Security:loginRedirect }
    
login_check:
    path: /login_check
    
pg_mcd_frontend:
    resource: "@PGMcdFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

pg_mcd_backend:
    resource: "@PGMcdBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"