security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    firewalls:
        login_firewall:
            pattern:   ^/login
            anonymous: ~
    providers:
        main:
            entity:
                class: PG\Mcd\EntityBundle\Entity\User
                property: username
    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12